// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using EducationalWebApplication.Data;

#nullable disable

namespace EducationalWebApplication.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("MinDegree")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 4,
                            Degree = 100,
                            DepartmentID = 1,
                            MinDegree = 40,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            Id = 2,
                            Credits = 3,
                            Degree = 100,
                            DepartmentID = 1,
                            MinDegree = 50,
                            Name = "Deep Learning"
                        },
                        new
                        {
                            Id = 3,
                            Credits = 3,
                            Degree = 100,
                            DepartmentID = 2,
                            MinDegree = 40,
                            Name = "Linear Algebra"
                        },
                        new
                        {
                            Id = 4,
                            Credits = 4,
                            Degree = 100,
                            DepartmentID = 2,
                            MinDegree = 50,
                            Name = "Data Science Tools"
                        });
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.CourseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("TraineeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("TraineeID");

                    b.ToTable("CourseResults");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseID = 1,
                            Score = 90,
                            TraineeID = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseID = 1,
                            Score = 95,
                            TraineeID = 2
                        },
                        new
                        {
                            Id = 3,
                            CourseID = 2,
                            Score = 92,
                            TraineeID = 3
                        },
                        new
                        {
                            Id = 4,
                            CourseID = 2,
                            Score = 100,
                            TraineeID = 4
                        },
                        new
                        {
                            Id = 5,
                            CourseID = 3,
                            Score = 80,
                            TraineeID = 5
                        },
                        new
                        {
                            Id = 6,
                            CourseID = 3,
                            Score = 86,
                            TraineeID = 6
                        },
                        new
                        {
                            Id = 7,
                            CourseID = 4,
                            Score = 99,
                            TraineeID = 7
                        },
                        new
                        {
                            Id = 8,
                            CourseID = 4,
                            Score = 100,
                            TraineeID = 8
                        });
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagerName = "Mohamed",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 2,
                            ManagerName = "Farida",
                            Name = "Data Science"
                        });
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CourseID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alex",
                            CourseID = 1,
                            DepartmentID = 1,
                            ImageURL = "1.jpg",
                            Name = "Ali",
                            Salary = 20000.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Cairo",
                            CourseID = 2,
                            DepartmentID = 1,
                            ImageURL = "2.jpg",
                            Name = "Ahmed",
                            Salary = 25000.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alex",
                            CourseID = 3,
                            DepartmentID = 2,
                            ImageURL = "3.jpg",
                            Name = "Mahmoud",
                            Salary = 21000.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Alex",
                            CourseID = 4,
                            DepartmentID = 2,
                            ImageURL = "4.jpg",
                            Name = "Aya",
                            Salary = 19000.0
                        });
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alex",
                            DepartmentID = 1,
                            Grade = 3,
                            ImageURL = "11.jpg",
                            Name = "Marina"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Alex",
                            DepartmentID = 1,
                            Grade = 2,
                            ImageURL = "22.jpg",
                            Name = "Karim"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alex",
                            DepartmentID = 1,
                            Grade = 3,
                            ImageURL = "33.jpg",
                            Name = "Salma"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Alex",
                            DepartmentID = 1,
                            Grade = 4,
                            ImageURL = "44.jpg",
                            Name = "Aysel"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Alex",
                            DepartmentID = 2,
                            Grade = 3,
                            ImageURL = "55.jpg",
                            Name = "Seif"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Alex",
                            DepartmentID = 2,
                            Grade = 1,
                            ImageURL = "66.jpg",
                            Name = "Amir"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Alex",
                            DepartmentID = 2,
                            Grade = 5,
                            ImageURL = "77.jpg",
                            Name = "Mostafa"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Alex",
                            DepartmentID = 2,
                            Grade = 2,
                            ImageURL = "88.jpg",
                            Name = "Fady"
                        });
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Course", b =>
                {
                    b.HasOne("WebAppAssignmentITIDay2.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.CourseResult", b =>
                {
                    b.HasOne("WebAppAssignmentITIDay2.Models.Course", "Course")
                        .WithMany("CourseResults")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppAssignmentITIDay2.Models.Trainee", "Trainee")
                        .WithMany("CourseResults")
                        .HasForeignKey("TraineeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Instructor", b =>
                {
                    b.HasOne("WebAppAssignmentITIDay2.Models.Course", "Course")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppAssignmentITIDay2.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Trainee", b =>
                {
                    b.HasOne("WebAppAssignmentITIDay2.Models.Department", "Department")
                        .WithMany("Trainees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Course", b =>
                {
                    b.Navigation("CourseResults");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("WebAppAssignmentITIDay2.Models.Trainee", b =>
                {
                    b.Navigation("CourseResults");
                });
#pragma warning restore 612, 618
        }
    }
}
